/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Analysis {
  public static int LLVMVerifyModule(SWIGTYPE_p_LLVMModuleRef M, LLVMVerifierFailureAction Action, SWIGTYPE_p_p_char OutMessage) {
    return AnalysisJNI.LLVMVerifyModule(SWIGTYPE_p_LLVMModuleRef.getCPtr(M), Action.swigValue(), SWIGTYPE_p_p_char.getCPtr(OutMessage));
  }

  public static int LLVMVerifyFunction(SWIGTYPE_p_LLVMValueRef Fn, LLVMVerifierFailureAction Action) {
    return AnalysisJNI.LLVMVerifyFunction(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn), Action.swigValue());
  }

  public static void LLVMViewFunctionCFG(SWIGTYPE_p_LLVMValueRef Fn) {
    AnalysisJNI.LLVMViewFunctionCFG(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn));
  }

  public static void LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMValueRef Fn) {
    AnalysisJNI.LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn));
  }

}
