/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Analysis {
  public static SWIGTYPE_p_p_char new_StringArray(int nelements) {
    long cPtr = AnalysisJNI.new_StringArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static void delete_StringArray(SWIGTYPE_p_p_char ary) {
    AnalysisJNI.delete_StringArray(SWIGTYPE_p_p_char.getCPtr(ary));
  }

  public static String StringArray_getitem(SWIGTYPE_p_p_char ary, int index) {
    return AnalysisJNI.StringArray_getitem(SWIGTYPE_p_p_char.getCPtr(ary), index);
  }

  public static void StringArray_setitem(SWIGTYPE_p_p_char ary, int index, String value) {
    AnalysisJNI.StringArray_setitem(SWIGTYPE_p_p_char.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_LLVMBool LLVMVerifyModule(SWIGTYPE_p_LLVMModuleRef M, LLVMVerifierFailureAction Action, SWIGTYPE_p_p_char OutMessage) {
    return new SWIGTYPE_p_LLVMBool(AnalysisJNI.LLVMVerifyModule(SWIGTYPE_p_LLVMModuleRef.getCPtr(M), Action.swigValue(), SWIGTYPE_p_p_char.getCPtr(OutMessage)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMVerifyFunction(SWIGTYPE_p_LLVMValueRef Fn, LLVMVerifierFailureAction Action) {
    return new SWIGTYPE_p_LLVMBool(AnalysisJNI.LLVMVerifyFunction(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn), Action.swigValue()), true);
  }

  public static void LLVMViewFunctionCFG(SWIGTYPE_p_LLVMValueRef Fn) {
    AnalysisJNI.LLVMViewFunctionCFG(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn));
  }

  public static void LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMValueRef Fn) {
    AnalysisJNI.LLVMViewFunctionCFGOnly(SWIGTYPE_p_LLVMValueRef.getCPtr(Fn));
  }

}
