/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class AnalysisJNI {
  public final static native long LLVMVerifyModule(long jarg1, int jarg2, long jarg3);
  public final static native long LLVMVerifyFunction(long jarg1, int jarg2);
  public final static native void LLVMViewFunctionCFG(long jarg1);
  public final static native void LLVMViewFunctionCFGOnly(long jarg1);
}
