/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdbool.h>
#include <llvm-c/BitReader.h>


static LLVMModuleRef *new_LLVMModuleRefArray(int nelements) { 
  return (LLVMModuleRef *) calloc(nelements,sizeof(LLVMModuleRef)); 
}

static void delete_LLVMModuleRefArray(LLVMModuleRef *ary) { 
  free(ary); 
}

static LLVMModuleRef LLVMModuleRefArray_getitem(LLVMModuleRef *ary, int index) {
    return ary[index];
}
static void LLVMModuleRefArray_setitem(LLVMModuleRef *ary, int index, LLVMModuleRef value) {
    ary[index] = value;
}


static char * *new_StringArray(int nelements) { 
  return (char * *) calloc(nelements,sizeof(char *)); 
}

static void delete_StringArray(char * *ary) { 
  free(ary); 
}

static char * StringArray_getitem(char * *ary, int index) {
    return ary[index];
}
static void StringArray_setitem(char * *ary, int index, char * value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_BitReaderJNI_new_1LLVMModuleRefArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  LLVMModuleRef *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (LLVMModuleRef *)new_LLVMModuleRefArray(arg1);
  *(LLVMModuleRef **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_BitReaderJNI_delete_1LLVMModuleRefArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  LLVMModuleRef *arg1 = (LLVMModuleRef *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMModuleRef **)&jarg1; 
  delete_LLVMModuleRefArray(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMModuleRefArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  LLVMModuleRef *arg1 = (LLVMModuleRef *) 0 ;
  int arg2 ;
  LLVMModuleRef result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMModuleRef **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (LLVMModuleRef)LLVMModuleRefArray_getitem(arg1,arg2);
  *(LLVMModuleRef *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMModuleRefArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  LLVMModuleRef *arg1 = (LLVMModuleRef *) 0 ;
  int arg2 ;
  LLVMModuleRef arg3 = (LLVMModuleRef) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMModuleRef **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(LLVMModuleRef *)&jarg3; 
  LLVMModuleRefArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_BitReaderJNI_new_1StringArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char **)new_StringArray(arg1);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_BitReaderJNI_delete_1StringArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  char **arg1 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  delete_StringArray(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_BitReaderJNI_StringArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jstring jresult = 0 ;
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)StringArray_getitem(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_BitReaderJNI_StringArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3) {
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  StringArray_setitem(arg1,arg2,arg3);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMParseBitcode(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  LLVMMemoryBufferRef arg1 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleRef *arg2 = (LLVMModuleRef *) 0 ;
  char **arg3 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMMemoryBufferRef *)&jarg1; 
  arg2 = *(LLVMModuleRef **)&jarg2; 
  arg3 = *(char ***)&jarg3; 
  result = (LLVMBool)LLVMParseBitcode(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMParseBitcodeInContext(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  LLVMContextRef arg1 = (LLVMContextRef) 0 ;
  LLVMMemoryBufferRef arg2 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleRef *arg3 = (LLVMModuleRef *) 0 ;
  char **arg4 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMContextRef *)&jarg1; 
  arg2 = *(LLVMMemoryBufferRef *)&jarg2; 
  arg3 = *(LLVMModuleRef **)&jarg3; 
  arg4 = *(char ***)&jarg4; 
  result = (LLVMBool)LLVMParseBitcodeInContext(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMGetBitcodeModuleInContext(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  LLVMContextRef arg1 = (LLVMContextRef) 0 ;
  LLVMMemoryBufferRef arg2 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleRef *arg3 = (LLVMModuleRef *) 0 ;
  char **arg4 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMContextRef *)&jarg1; 
  arg2 = *(LLVMMemoryBufferRef *)&jarg2; 
  arg3 = *(LLVMModuleRef **)&jarg3; 
  arg4 = *(char ***)&jarg4; 
  result = (LLVMBool)LLVMGetBitcodeModuleInContext(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMGetBitcodeModule(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  LLVMMemoryBufferRef arg1 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleRef *arg2 = (LLVMModuleRef *) 0 ;
  char **arg3 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMMemoryBufferRef *)&jarg1; 
  arg2 = *(LLVMModuleRef **)&jarg2; 
  arg3 = *(char ***)&jarg3; 
  result = (LLVMBool)LLVMGetBitcodeModule(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMGetBitcodeModuleProviderInContext(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  LLVMContextRef arg1 = (LLVMContextRef) 0 ;
  LLVMMemoryBufferRef arg2 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleProviderRef *arg3 = (LLVMModuleProviderRef *) 0 ;
  char **arg4 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMContextRef *)&jarg1; 
  arg2 = *(LLVMMemoryBufferRef *)&jarg2; 
  arg3 = *(LLVMModuleProviderRef **)&jarg3; 
  arg4 = *(char ***)&jarg4; 
  result = (LLVMBool)LLVMGetBitcodeModuleProviderInContext(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_BitReaderJNI_LLVMGetBitcodeModuleProvider(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  LLVMMemoryBufferRef arg1 = (LLVMMemoryBufferRef) 0 ;
  LLVMModuleProviderRef *arg2 = (LLVMModuleProviderRef *) 0 ;
  char **arg3 = (char **) 0 ;
  LLVMBool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMMemoryBufferRef *)&jarg1; 
  arg2 = *(LLVMModuleProviderRef **)&jarg2; 
  arg3 = *(char ***)&jarg3; 
  result = (LLVMBool)LLVMGetBitcodeModuleProvider(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

