/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Disassembler implements DisassemblerConstants {
  public static SWIGTYPE_p_void LLVMCreateDisasm(String TripleName, SWIGTYPE_p_void DisInfo, int TagType, SWIGTYPE_p_f_p_void_uint64_t_uint64_t_uint64_t_int_p_void__int GetOpInfo, SWIGTYPE_p_f_p_void_uint64_t_p_uint64_t_uint64_t_p_p_q_const__char__p_char SymbolLookUp) {
    long cPtr = DisassemblerJNI.LLVMCreateDisasm(TripleName, SWIGTYPE_p_void.getCPtr(DisInfo), TagType, SWIGTYPE_p_f_p_void_uint64_t_uint64_t_uint64_t_int_p_void__int.getCPtr(GetOpInfo), SWIGTYPE_p_f_p_void_uint64_t_p_uint64_t_uint64_t_p_p_q_const__char__p_char.getCPtr(SymbolLookUp));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void LLVMDisasmDispose(SWIGTYPE_p_void DC) {
    DisassemblerJNI.LLVMDisasmDispose(SWIGTYPE_p_void.getCPtr(DC));
  }

  public static long LLVMDisasmInstruction(SWIGTYPE_p_void DC, SWIGTYPE_p_uint8_t Bytes, SWIGTYPE_p_uint64_t BytesSize, SWIGTYPE_p_uint64_t PC, String OutString, long OutStringSize) {
    return DisassemblerJNI.LLVMDisasmInstruction(SWIGTYPE_p_void.getCPtr(DC), SWIGTYPE_p_uint8_t.getCPtr(Bytes), SWIGTYPE_p_uint64_t.getCPtr(BytesSize), SWIGTYPE_p_uint64_t.getCPtr(PC), OutString, OutStringSize);
  }

}
