/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <llvm-c/Disassembler.h>


static char * *new_StringArray(int nelements) { 
  return (char * *) calloc(nelements,sizeof(char *)); 
}

static void delete_StringArray(char * *ary) { 
  free(ary); 
}

static char * StringArray_getitem(char * *ary, int index) {
    return ary[index];
}
static void StringArray_setitem(char * *ary, int index, char * value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_new_1StringArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char **)new_StringArray(arg1);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_delete_1StringArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  char **arg1 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  delete_StringArray(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_DisassemblerJNI_StringArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jstring jresult = 0 ;
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)StringArray_getitem(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_StringArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3) {
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  StringArray_setitem(arg1,arg2,arg3);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Present_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Present = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Present_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  result =  ((arg1)->Present);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg2) {
      arg1->Name = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->Name, (const char *)arg2);
    } else {
      arg1->Name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  result = (char *) ((arg1)->Name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Value = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfoSymbol1_1Value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  result =  ((arg1)->Value);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_new_1LLVMOpInfoSymbol1(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct LLVMOpInfoSymbol1 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct LLVMOpInfoSymbol1 *)calloc(1, sizeof(struct LLVMOpInfoSymbol1));
  *(struct LLVMOpInfoSymbol1 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_delete_1LLVMOpInfoSymbol1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct LLVMOpInfoSymbol1 *arg1 = (struct LLVMOpInfoSymbol1 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct LLVMOpInfoSymbol1 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1AddSymbol_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  struct LLVMOpInfoSymbol1 *arg2 = (struct LLVMOpInfoSymbol1 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  arg2 = *(struct LLVMOpInfoSymbol1 **)&jarg2; 
  if (arg1) (arg1)->AddSymbol = *arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1AddSymbol_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  struct LLVMOpInfoSymbol1 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  result = (struct LLVMOpInfoSymbol1 *)& ((arg1)->AddSymbol);
  *(struct LLVMOpInfoSymbol1 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1SubtractSymbol_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  struct LLVMOpInfoSymbol1 *arg2 = (struct LLVMOpInfoSymbol1 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  arg2 = *(struct LLVMOpInfoSymbol1 **)&jarg2; 
  if (arg1) (arg1)->SubtractSymbol = *arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1SubtractSymbol_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  struct LLVMOpInfoSymbol1 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  result = (struct LLVMOpInfoSymbol1 *)& ((arg1)->SubtractSymbol);
  *(struct LLVMOpInfoSymbol1 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1Value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->Value = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1Value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  result =  ((arg1)->Value);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1VariantKind_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  uint64_t arg2 ;
  uint64_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  argp2 = *(uint64_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->VariantKind = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMOpInfo1_1VariantKind_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  result =  ((arg1)->VariantKind);
  {
    uint64_t * resultptr = (uint64_t *) malloc(sizeof(uint64_t));
    memmove(resultptr, &result, sizeof(uint64_t));
    *(uint64_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_new_1LLVMOpInfo1(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct LLVMOpInfo1 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct LLVMOpInfo1 *)calloc(1, sizeof(struct LLVMOpInfo1));
  *(struct LLVMOpInfo1 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_delete_1LLVMOpInfo1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct LLVMOpInfo1 *arg1 = (struct LLVMOpInfo1 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct LLVMOpInfo1 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1VariantKind_1None_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1VariantKind_1ARM_1HI16_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1VariantKind_1ARM_1LO16_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1InOut_1None_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1In_1Branch_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1In_1PCrel_1Load_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1Out_1SymbolStub_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1Out_1LitPool_1SymAddr_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisassembler_1ReferenceType_1Out_1LitPool_1CstrAddr_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMCreateDisasm(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  LLVMOpInfoCallback arg4 = (LLVMOpInfoCallback) 0 ;
  LLVMSymbolLookupCallback arg5 = (LLVMSymbolLookupCallback) 0 ;
  LLVMDisasmContextRef result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(void **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(LLVMOpInfoCallback *)&jarg4; 
  arg5 = *(LLVMSymbolLookupCallback *)&jarg5; 
  result = (LLVMDisasmContextRef)LLVMCreateDisasm((char const *)arg1,arg2,arg3,arg4,(char const *(*)(void *,uint64_t,uint64_t *,uint64_t,char const **))arg5);
  *(LLVMDisasmContextRef *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisasmDispose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  LLVMDisasmContextRef arg1 = (LLVMDisasmContextRef) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMDisasmContextRef *)&jarg1; 
  LLVMDisasmDispose(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_DisassemblerJNI_LLVMDisasmInstruction(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jstring jarg5, jlong jarg6) {
  jlong jresult = 0 ;
  LLVMDisasmContextRef arg1 = (LLVMDisasmContextRef) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  uint64_t arg3 ;
  uint64_t arg4 ;
  char *arg5 = (char *) 0 ;
  size_t arg6 ;
  uint64_t *argp3 ;
  uint64_t *argp4 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LLVMDisasmContextRef *)&jarg1; 
  arg2 = *(uint8_t **)&jarg2; 
  argp3 = *(uint64_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(uint64_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg4 = *argp4; 
  arg5 = 0;
  if (jarg5) {
    arg5 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0);
    if (!arg5) return 0;
  }
  arg6 = (size_t)jarg6; 
  result = LLVMDisasmInstruction(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jlong)result; 
  if (arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, (const char *)arg5);
  return jresult;
}


#ifdef __cplusplus
}
#endif

