/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class DisassemblerJNI {
  public final static native long new_StringArray(int jarg1);
  public final static native void delete_StringArray(long jarg1);
  public final static native String StringArray_getitem(long jarg1, int jarg2);
  public final static native void StringArray_setitem(long jarg1, int jarg2, String jarg3);
  public final static native void LLVMOpInfoSymbol1_Present_set(long jarg1, LLVMOpInfoSymbol1 jarg1_, long jarg2);
  public final static native long LLVMOpInfoSymbol1_Present_get(long jarg1, LLVMOpInfoSymbol1 jarg1_);
  public final static native void LLVMOpInfoSymbol1_Name_set(long jarg1, LLVMOpInfoSymbol1 jarg1_, String jarg2);
  public final static native String LLVMOpInfoSymbol1_Name_get(long jarg1, LLVMOpInfoSymbol1 jarg1_);
  public final static native void LLVMOpInfoSymbol1_Value_set(long jarg1, LLVMOpInfoSymbol1 jarg1_, long jarg2);
  public final static native long LLVMOpInfoSymbol1_Value_get(long jarg1, LLVMOpInfoSymbol1 jarg1_);
  public final static native long new_LLVMOpInfoSymbol1();
  public final static native void delete_LLVMOpInfoSymbol1(long jarg1);
  public final static native void LLVMOpInfo1_AddSymbol_set(long jarg1, LLVMOpInfo1 jarg1_, long jarg2, LLVMOpInfoSymbol1 jarg2_);
  public final static native long LLVMOpInfo1_AddSymbol_get(long jarg1, LLVMOpInfo1 jarg1_);
  public final static native void LLVMOpInfo1_SubtractSymbol_set(long jarg1, LLVMOpInfo1 jarg1_, long jarg2, LLVMOpInfoSymbol1 jarg2_);
  public final static native long LLVMOpInfo1_SubtractSymbol_get(long jarg1, LLVMOpInfo1 jarg1_);
  public final static native void LLVMOpInfo1_Value_set(long jarg1, LLVMOpInfo1 jarg1_, long jarg2);
  public final static native long LLVMOpInfo1_Value_get(long jarg1, LLVMOpInfo1 jarg1_);
  public final static native void LLVMOpInfo1_VariantKind_set(long jarg1, LLVMOpInfo1 jarg1_, long jarg2);
  public final static native long LLVMOpInfo1_VariantKind_get(long jarg1, LLVMOpInfo1 jarg1_);
  public final static native long new_LLVMOpInfo1();
  public final static native void delete_LLVMOpInfo1(long jarg1);
  public final static native int LLVMDisassembler_VariantKind_None_get();
  public final static native int LLVMDisassembler_VariantKind_ARM_HI16_get();
  public final static native int LLVMDisassembler_VariantKind_ARM_LO16_get();
  public final static native int LLVMDisassembler_ReferenceType_InOut_None_get();
  public final static native int LLVMDisassembler_ReferenceType_In_Branch_get();
  public final static native int LLVMDisassembler_ReferenceType_In_PCrel_Load_get();
  public final static native int LLVMDisassembler_ReferenceType_Out_SymbolStub_get();
  public final static native int LLVMDisassembler_ReferenceType_Out_LitPool_SymAddr_get();
  public final static native int LLVMDisassembler_ReferenceType_Out_LitPool_CstrAddr_get();
  public final static native long LLVMCreateDisasm(String jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
  public final static native void LLVMDisasmDispose(long jarg1);
  public final static native long LLVMDisasmInstruction(long jarg1, long jarg2, long jarg3, long jarg4, String jarg5, long jarg6);
}
