/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public interface DisassemblerConstants {
  public final static int LLVMDisassembler_VariantKind_None = DisassemblerJNI.LLVMDisassembler_VariantKind_None_get();
  public final static int LLVMDisassembler_VariantKind_ARM_HI16 = DisassemblerJNI.LLVMDisassembler_VariantKind_ARM_HI16_get();
  public final static int LLVMDisassembler_VariantKind_ARM_LO16 = DisassemblerJNI.LLVMDisassembler_VariantKind_ARM_LO16_get();
  public final static int LLVMDisassembler_ReferenceType_InOut_None = DisassemblerJNI.LLVMDisassembler_ReferenceType_InOut_None_get();
  public final static int LLVMDisassembler_ReferenceType_In_Branch = DisassemblerJNI.LLVMDisassembler_ReferenceType_In_Branch_get();
  public final static int LLVMDisassembler_ReferenceType_In_PCrel_Load = DisassemblerJNI.LLVMDisassembler_ReferenceType_In_PCrel_Load_get();
  public final static int LLVMDisassembler_ReferenceType_Out_SymbolStub = DisassemblerJNI.LLVMDisassembler_ReferenceType_Out_SymbolStub_get();
  public final static int LLVMDisassembler_ReferenceType_Out_LitPool_SymAddr = DisassemblerJNI.LLVMDisassembler_ReferenceType_Out_LitPool_SymAddr_get();
  public final static int LLVMDisassembler_ReferenceType_Out_LitPool_CstrAddr = DisassemblerJNI.LLVMDisassembler_ReferenceType_Out_LitPool_CstrAddr_get();
}
