/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public interface EnhancedDisassemblyConstants {
  public final static int kEDAssemblySyntaxX86Intel = EnhancedDisassemblyJNI.kEDAssemblySyntaxX86Intel_get();
  public final static int kEDAssemblySyntaxX86ATT = EnhancedDisassemblyJNI.kEDAssemblySyntaxX86ATT_get();
  public final static int kEDAssemblySyntaxARMUAL = EnhancedDisassemblyJNI.kEDAssemblySyntaxARMUAL_get();

}
