/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class EnhancedDisassemblyJNI {
  public final static native long new_UnsignedIntArray(int jarg1);
  public final static native void delete_UnsignedIntArray(long jarg1);
  public final static native long UnsignedIntArray_getitem(long jarg1, int jarg2);
  public final static native void UnsignedIntArray_setitem(long jarg1, int jarg2, long jarg3);
  public final static native long new_StringArray(int jarg1);
  public final static native void delete_StringArray(long jarg1);
  public final static native String StringArray_getitem(long jarg1, int jarg2);
  public final static native void StringArray_setitem(long jarg1, int jarg2, String jarg3);
  public final static native int kEDAssemblySyntaxX86Intel_get();
  public final static native int kEDAssemblySyntaxX86ATT_get();
  public final static native int kEDAssemblySyntaxARMUAL_get();
  public final static native int EDGetDisassembler(long jarg1, String jarg2, long jarg3);
  public final static native int EDGetRegisterName(long jarg1, long jarg2, long jarg3);
  public final static native int EDRegisterIsStackPointer(long jarg1, long jarg2);
  public final static native int EDRegisterIsProgramCounter(long jarg1, long jarg2);
  public final static native long EDCreateInsts(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6);
  public final static native void EDReleaseInst(long jarg1);
  public final static native int EDInstByteSize(long jarg1);
  public final static native int EDGetInstString(long jarg1, long jarg2);
  public final static native int EDInstID(long jarg1, long jarg2);
  public final static native int EDInstIsBranch(long jarg1);
  public final static native int EDInstIsMove(long jarg1);
  public final static native int EDBranchTargetID(long jarg1);
  public final static native int EDMoveSourceID(long jarg1);
  public final static native int EDMoveTargetID(long jarg1);
  public final static native int EDNumTokens(long jarg1);
  public final static native int EDGetToken(long jarg1, long jarg2, int jarg3);
  public final static native int EDGetTokenString(long jarg1, long jarg2);
  public final static native int EDOperandIndexForToken(long jarg1);
  public final static native int EDTokenIsWhitespace(long jarg1);
  public final static native int EDTokenIsPunctuation(long jarg1);
  public final static native int EDTokenIsOpcode(long jarg1);
  public final static native int EDTokenIsLiteral(long jarg1);
  public final static native int EDTokenIsRegister(long jarg1);
  public final static native int EDTokenIsNegativeLiteral(long jarg1);
  public final static native int EDLiteralTokenAbsoluteValue(long jarg1, long jarg2);
  public final static native int EDRegisterTokenValue(long jarg1, long jarg2);
  public final static native int EDNumOperands(long jarg1);
  public final static native int EDGetOperand(long jarg1, long jarg2, int jarg3);
  public final static native int EDOperandIsRegister(long jarg1);
  public final static native int EDOperandIsImmediate(long jarg1);
  public final static native int EDOperandIsMemory(long jarg1);
  public final static native int EDRegisterOperandValue(long jarg1, long jarg2);
  public final static native int EDImmediateOperandValue(long jarg1, long jarg2);
  public final static native int EDEvaluateOperand(long jarg1, long jarg2, long jarg3, long jarg4);
}
