/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class ExecutionEngine {
  public static SWIGTYPE_p_LLVMValueRef new_LLVMValueRefArray(int nelements) {
    long cPtr = ExecutionEngineJNI.new_LLVMValueRefArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMValueRef(cPtr, false);
  }

  public static void delete_LLVMValueRefArray(SWIGTYPE_p_LLVMValueRef ary) {
    ExecutionEngineJNI.delete_LLVMValueRefArray(SWIGTYPE_p_LLVMValueRef.getCPtr(ary));
  }

  public static SWIGTYPE_p_LLVMValueRef LLVMValueRefArray_getitem(SWIGTYPE_p_LLVMValueRef ary, int index) {
    return new SWIGTYPE_p_LLVMValueRef(ExecutionEngineJNI.LLVMValueRefArray_getitem(SWIGTYPE_p_LLVMValueRef.getCPtr(ary), index), true);
  }

  public static void LLVMValueRefArray_setitem(SWIGTYPE_p_LLVMValueRef ary, int index, SWIGTYPE_p_LLVMValueRef value) {
    ExecutionEngineJNI.LLVMValueRefArray_setitem(SWIGTYPE_p_LLVMValueRef.getCPtr(ary), index, SWIGTYPE_p_LLVMValueRef.getCPtr(value));
  }

  public static void LLVMLinkInJIT() {
    ExecutionEngineJNI.LLVMLinkInJIT();
  }

  public static void LLVMLinkInInterpreter() {
    ExecutionEngineJNI.LLVMLinkInInterpreter();
  }

  public static SWIGTYPE_p_LLVMOpaqueGenericValue LLVMCreateGenericValueOfInt(SWIGTYPE_p_LLVMTypeRef Ty, java.math.BigInteger N, SWIGTYPE_p_LLVMBool IsSigned) {
    long cPtr = ExecutionEngineJNI.LLVMCreateGenericValueOfInt(SWIGTYPE_p_LLVMTypeRef.getCPtr(Ty), N, SWIGTYPE_p_LLVMBool.getCPtr(IsSigned));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueGenericValue(cPtr, false);
  }

  public static SWIGTYPE_p_LLVMOpaqueGenericValue LLVMCreateGenericValueOfPointer(SWIGTYPE_p_void P) {
    long cPtr = ExecutionEngineJNI.LLVMCreateGenericValueOfPointer(SWIGTYPE_p_void.getCPtr(P));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueGenericValue(cPtr, false);
  }

  public static SWIGTYPE_p_LLVMOpaqueGenericValue LLVMCreateGenericValueOfFloat(SWIGTYPE_p_LLVMTypeRef Ty, double N) {
    long cPtr = ExecutionEngineJNI.LLVMCreateGenericValueOfFloat(SWIGTYPE_p_LLVMTypeRef.getCPtr(Ty), N);
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueGenericValue(cPtr, false);
  }

  public static long LLVMGenericValueIntWidth(SWIGTYPE_p_LLVMOpaqueGenericValue GenValRef) {
    return ExecutionEngineJNI.LLVMGenericValueIntWidth(SWIGTYPE_p_LLVMOpaqueGenericValue.getCPtr(GenValRef));
  }

  public static java.math.BigInteger LLVMGenericValueToInt(SWIGTYPE_p_LLVMOpaqueGenericValue GenVal, SWIGTYPE_p_LLVMBool IsSigned) {
    return ExecutionEngineJNI.LLVMGenericValueToInt(SWIGTYPE_p_LLVMOpaqueGenericValue.getCPtr(GenVal), SWIGTYPE_p_LLVMBool.getCPtr(IsSigned));
  }

  public static SWIGTYPE_p_void LLVMGenericValueToPointer(SWIGTYPE_p_LLVMOpaqueGenericValue GenVal) {
    long cPtr = ExecutionEngineJNI.LLVMGenericValueToPointer(SWIGTYPE_p_LLVMOpaqueGenericValue.getCPtr(GenVal));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static double LLVMGenericValueToFloat(SWIGTYPE_p_LLVMTypeRef TyRef, SWIGTYPE_p_LLVMOpaqueGenericValue GenVal) {
    return ExecutionEngineJNI.LLVMGenericValueToFloat(SWIGTYPE_p_LLVMTypeRef.getCPtr(TyRef), SWIGTYPE_p_LLVMOpaqueGenericValue.getCPtr(GenVal));
  }

  public static void LLVMDisposeGenericValue(SWIGTYPE_p_LLVMOpaqueGenericValue GenVal) {
    ExecutionEngineJNI.LLVMDisposeGenericValue(SWIGTYPE_p_LLVMOpaqueGenericValue.getCPtr(GenVal));
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateExecutionEngineForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutEE, SWIGTYPE_p_LLVMModuleRef M, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateExecutionEngineForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutEE), SWIGTYPE_p_LLVMModuleRef.getCPtr(M), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateInterpreterForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutInterp, SWIGTYPE_p_LLVMModuleRef M, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateInterpreterForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutInterp), SWIGTYPE_p_LLVMModuleRef.getCPtr(M), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateJITCompilerForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutJIT, SWIGTYPE_p_LLVMModuleRef M, long OptLevel, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateJITCompilerForModule(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutJIT), SWIGTYPE_p_LLVMModuleRef.getCPtr(M), OptLevel, SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateExecutionEngine(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutEE, SWIGTYPE_p_LLVMModuleProviderRef MP, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateExecutionEngine(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutEE), SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateInterpreter(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutInterp, SWIGTYPE_p_LLVMModuleProviderRef MP, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateInterpreter(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutInterp), SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMCreateJITCompiler(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine OutJIT, SWIGTYPE_p_LLVMModuleProviderRef MP, long OptLevel, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMCreateJITCompiler(SWIGTYPE_p_p_LLVMOpaqueExecutionEngine.getCPtr(OutJIT), SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP), OptLevel, SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static void LLVMDisposeExecutionEngine(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE) {
    ExecutionEngineJNI.LLVMDisposeExecutionEngine(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE));
  }

  public static void LLVMRunStaticConstructors(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE) {
    ExecutionEngineJNI.LLVMRunStaticConstructors(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE));
  }

  public static void LLVMRunStaticDestructors(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE) {
    ExecutionEngineJNI.LLVMRunStaticDestructors(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE));
  }

  public static int LLVMRunFunctionAsMain(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef F, long ArgC, SWIGTYPE_p_p_char ArgV, SWIGTYPE_p_p_char EnvP) {
    return ExecutionEngineJNI.LLVMRunFunctionAsMain(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(F), ArgC, SWIGTYPE_p_p_char.getCPtr(ArgV), SWIGTYPE_p_p_char.getCPtr(EnvP));
  }

  public static SWIGTYPE_p_LLVMOpaqueGenericValue LLVMRunFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef F, long NumArgs, SWIGTYPE_p_p_LLVMOpaqueGenericValue Args) {
    long cPtr = ExecutionEngineJNI.LLVMRunFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(F), NumArgs, SWIGTYPE_p_p_LLVMOpaqueGenericValue.getCPtr(Args));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueGenericValue(cPtr, false);
  }

  public static void LLVMFreeMachineCodeForFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef F) {
    ExecutionEngineJNI.LLVMFreeMachineCodeForFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(F));
  }

  public static void LLVMAddModule(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMModuleRef M) {
    ExecutionEngineJNI.LLVMAddModule(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMModuleRef.getCPtr(M));
  }

  public static void LLVMAddModuleProvider(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMModuleProviderRef MP) {
    ExecutionEngineJNI.LLVMAddModuleProvider(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP));
  }

  public static SWIGTYPE_p_LLVMBool LLVMRemoveModule(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMModuleRef M, SWIGTYPE_p_LLVMModuleRef OutMod, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMRemoveModule(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMModuleRef.getCPtr(M), SWIGTYPE_p_LLVMModuleRef.getCPtr(OutMod), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMRemoveModuleProvider(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMModuleProviderRef MP, SWIGTYPE_p_LLVMModuleRef OutMod, SWIGTYPE_p_p_char OutError) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMRemoveModuleProvider(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP), SWIGTYPE_p_LLVMModuleRef.getCPtr(OutMod), SWIGTYPE_p_p_char.getCPtr(OutError)), true);
  }

  public static SWIGTYPE_p_LLVMBool LLVMFindFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, String Name, SWIGTYPE_p_LLVMValueRef OutFn) {
    return new SWIGTYPE_p_LLVMBool(ExecutionEngineJNI.LLVMFindFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), Name, SWIGTYPE_p_LLVMValueRef.getCPtr(OutFn)), true);
  }

  public static SWIGTYPE_p_void LLVMRecompileAndRelinkFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef Fn) {
    long cPtr = ExecutionEngineJNI.LLVMRecompileAndRelinkFunction(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(Fn));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_LLVMTargetDataRef LLVMGetExecutionEngineTargetData(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE) {
    return new SWIGTYPE_p_LLVMTargetDataRef(ExecutionEngineJNI.LLVMGetExecutionEngineTargetData(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE)), true);
  }

  public static void LLVMAddGlobalMapping(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef Global, SWIGTYPE_p_void Addr) {
    ExecutionEngineJNI.LLVMAddGlobalMapping(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(Global), SWIGTYPE_p_void.getCPtr(Addr));
  }

  public static SWIGTYPE_p_void LLVMGetPointerToGlobal(SWIGTYPE_p_LLVMOpaqueExecutionEngine EE, SWIGTYPE_p_LLVMValueRef Global) {
    long cPtr = ExecutionEngineJNI.LLVMGetPointerToGlobal(SWIGTYPE_p_LLVMOpaqueExecutionEngine.getCPtr(EE), SWIGTYPE_p_LLVMValueRef.getCPtr(Global));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
