/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class InitializationJNI {
  public final static native void LLVMInitializeTransformUtils(long jarg1);
  public final static native void LLVMInitializeScalarOpts(long jarg1);
  public final static native void LLVMInitializeVectorization(long jarg1);
  public final static native void LLVMInitializeInstCombine(long jarg1);
  public final static native void LLVMInitializeIPO(long jarg1);
  public final static native void LLVMInitializeInstrumentation(long jarg1);
  public final static native void LLVMInitializeAnalysis(long jarg1);
  public final static native void LLVMInitializeIPA(long jarg1);
  public final static native void LLVMInitializeCodeGen(long jarg1);
  public final static native void LLVMInitializeTarget(long jarg1);
}
