/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Initialization {
  public static void LLVMInitializeTransformUtils(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeTransformUtils(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeScalarOpts(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeScalarOpts(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeVectorization(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeVectorization(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeInstCombine(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeInstCombine(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeIPO(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeIPO(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeInstrumentation(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeInstrumentation(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeAnalysis(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeAnalysis(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeIPA(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeIPA(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeCodeGen(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeCodeGen(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeTarget(SWIGTYPE_p_LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeTarget(SWIGTYPE_p_LLVMOpaquePassRegistry.getCPtr(R));
  }

}
