/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class IPOJNI {
  public final static native void LLVMAddArgumentPromotionPass(long jarg1);
  public final static native void LLVMAddConstantMergePass(long jarg1);
  public final static native void LLVMAddDeadArgEliminationPass(long jarg1);
  public final static native void LLVMAddFunctionAttrsPass(long jarg1);
  public final static native void LLVMAddFunctionInliningPass(long jarg1);
  public final static native void LLVMAddAlwaysInlinerPass(long jarg1);
  public final static native void LLVMAddGlobalDCEPass(long jarg1);
  public final static native void LLVMAddGlobalOptimizerPass(long jarg1);
  public final static native void LLVMAddIPConstantPropagationPass(long jarg1);
  public final static native void LLVMAddPruneEHPass(long jarg1);
  public final static native void LLVMAddIPSCCPPass(long jarg1);
  public final static native void LLVMAddInternalizePass(long jarg1, long jarg2);
  public final static native void LLVMAddStripDeadPrototypesPass(long jarg1);
  public final static native void LLVMAddStripSymbolsPass(long jarg1);
}
