/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Linker {
  public static SWIGTYPE_p_p_char new_StringArray(int nelements) {
    long cPtr = LinkerJNI.new_StringArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static void delete_StringArray(SWIGTYPE_p_p_char ary) {
    LinkerJNI.delete_StringArray(SWIGTYPE_p_p_char.getCPtr(ary));
  }

  public static String StringArray_getitem(SWIGTYPE_p_p_char ary, int index) {
    return LinkerJNI.StringArray_getitem(SWIGTYPE_p_p_char.getCPtr(ary), index);
  }

  public static void StringArray_setitem(SWIGTYPE_p_p_char ary, int index, String value) {
    LinkerJNI.StringArray_setitem(SWIGTYPE_p_p_char.getCPtr(ary), index, value);
  }

  public static int LLVMLinkModules(SWIGTYPE_p_LLVMOpaqueModule Dest, SWIGTYPE_p_LLVMOpaqueModule Src, LLVMLinkerMode Mode, SWIGTYPE_p_p_char OutMessage) {
    return LinkerJNI.LLVMLinkModules(SWIGTYPE_p_LLVMOpaqueModule.getCPtr(Dest), SWIGTYPE_p_LLVMOpaqueModule.getCPtr(Src), Mode.swigValue(), SWIGTYPE_p_p_char.getCPtr(OutMessage));
  }

}
