/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class LinkerJNI {
  public final static native long new_StringArray(int jarg1);
  public final static native void delete_StringArray(long jarg1);
  public final static native String StringArray_getitem(long jarg1, int jarg2);
  public final static native void StringArray_setitem(long jarg1, int jarg2, String jarg3);
  public final static native int LLVMLinkerDestroySource_get();
  public final static native int LLVMLinkerPreserveSource_get();
  public final static native int LLVMLinkModules(long jarg1, long jarg2, int jarg3, long jarg4);
}
