/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class LLVMLandingPadClauseTy {
  public final static LLVMLandingPadClauseTy LLVMLandingPadCatch = new LLVMLandingPadClauseTy("LLVMLandingPadCatch");
  public final static LLVMLandingPadClauseTy LLVMLandingPadFilter = new LLVMLandingPadClauseTy("LLVMLandingPadFilter");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMLandingPadClauseTy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMLandingPadClauseTy.class + " with value " + swigValue);
  }

  private LLVMLandingPadClauseTy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMLandingPadClauseTy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMLandingPadClauseTy(String swigName, LLVMLandingPadClauseTy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMLandingPadClauseTy[] swigValues = { LLVMLandingPadCatch, LLVMLandingPadFilter };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

