/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class LLVMCodeGenOptLevel {
  public final static LLVMCodeGenOptLevel LLVMCodeGenLevelNone = new LLVMCodeGenOptLevel("LLVMCodeGenLevelNone");
  public final static LLVMCodeGenOptLevel LLVMCodeGenLevelLess = new LLVMCodeGenOptLevel("LLVMCodeGenLevelLess");
  public final static LLVMCodeGenOptLevel LLVMCodeGenLevelDefault = new LLVMCodeGenOptLevel("LLVMCodeGenLevelDefault");
  public final static LLVMCodeGenOptLevel LLVMCodeGenLevelAggressive = new LLVMCodeGenOptLevel("LLVMCodeGenLevelAggressive");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMCodeGenOptLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMCodeGenOptLevel.class + " with value " + swigValue);
  }

  private LLVMCodeGenOptLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMCodeGenOptLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMCodeGenOptLevel(String swigName, LLVMCodeGenOptLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMCodeGenOptLevel[] swigValues = { LLVMCodeGenLevelNone, LLVMCodeGenLevelLess, LLVMCodeGenLevelDefault, LLVMCodeGenLevelAggressive };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

