/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class LLVMRelocMode {
  public final static LLVMRelocMode LLVMRelocDefault = new LLVMRelocMode("LLVMRelocDefault");
  public final static LLVMRelocMode LLVMRelocStatic = new LLVMRelocMode("LLVMRelocStatic");
  public final static LLVMRelocMode LLVMRelocPIC = new LLVMRelocMode("LLVMRelocPIC");
  public final static LLVMRelocMode LLVMRelocDynamicNoPic = new LLVMRelocMode("LLVMRelocDynamicNoPic");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMRelocMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMRelocMode.class + " with value " + swigValue);
  }

  private LLVMRelocMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMRelocMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMRelocMode(String swigName, LLVMRelocMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMRelocMode[] swigValues = { LLVMRelocDefault, LLVMRelocStatic, LLVMRelocPIC, LLVMRelocDynamicNoPic };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

