/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class LLVMOpcode {
  public final static LLVMOpcode LLVMRet = new LLVMOpcode("LLVMRet", CoreJNI.LLVMRet_get());
  public final static LLVMOpcode LLVMBr = new LLVMOpcode("LLVMBr", CoreJNI.LLVMBr_get());
  public final static LLVMOpcode LLVMSwitch = new LLVMOpcode("LLVMSwitch", CoreJNI.LLVMSwitch_get());
  public final static LLVMOpcode LLVMIndirectBr = new LLVMOpcode("LLVMIndirectBr", CoreJNI.LLVMIndirectBr_get());
  public final static LLVMOpcode LLVMInvoke = new LLVMOpcode("LLVMInvoke", CoreJNI.LLVMInvoke_get());
  public final static LLVMOpcode LLVMUnreachable = new LLVMOpcode("LLVMUnreachable", CoreJNI.LLVMUnreachable_get());
  public final static LLVMOpcode LLVMAdd = new LLVMOpcode("LLVMAdd", CoreJNI.LLVMAdd_get());
  public final static LLVMOpcode LLVMFAdd = new LLVMOpcode("LLVMFAdd", CoreJNI.LLVMFAdd_get());
  public final static LLVMOpcode LLVMSub = new LLVMOpcode("LLVMSub", CoreJNI.LLVMSub_get());
  public final static LLVMOpcode LLVMFSub = new LLVMOpcode("LLVMFSub", CoreJNI.LLVMFSub_get());
  public final static LLVMOpcode LLVMMul = new LLVMOpcode("LLVMMul", CoreJNI.LLVMMul_get());
  public final static LLVMOpcode LLVMFMul = new LLVMOpcode("LLVMFMul", CoreJNI.LLVMFMul_get());
  public final static LLVMOpcode LLVMUDiv = new LLVMOpcode("LLVMUDiv", CoreJNI.LLVMUDiv_get());
  public final static LLVMOpcode LLVMSDiv = new LLVMOpcode("LLVMSDiv", CoreJNI.LLVMSDiv_get());
  public final static LLVMOpcode LLVMFDiv = new LLVMOpcode("LLVMFDiv", CoreJNI.LLVMFDiv_get());
  public final static LLVMOpcode LLVMURem = new LLVMOpcode("LLVMURem", CoreJNI.LLVMURem_get());
  public final static LLVMOpcode LLVMSRem = new LLVMOpcode("LLVMSRem", CoreJNI.LLVMSRem_get());
  public final static LLVMOpcode LLVMFRem = new LLVMOpcode("LLVMFRem", CoreJNI.LLVMFRem_get());
  public final static LLVMOpcode LLVMShl = new LLVMOpcode("LLVMShl", CoreJNI.LLVMShl_get());
  public final static LLVMOpcode LLVMLShr = new LLVMOpcode("LLVMLShr", CoreJNI.LLVMLShr_get());
  public final static LLVMOpcode LLVMAShr = new LLVMOpcode("LLVMAShr", CoreJNI.LLVMAShr_get());
  public final static LLVMOpcode LLVMAnd = new LLVMOpcode("LLVMAnd", CoreJNI.LLVMAnd_get());
  public final static LLVMOpcode LLVMOr = new LLVMOpcode("LLVMOr", CoreJNI.LLVMOr_get());
  public final static LLVMOpcode LLVMXor = new LLVMOpcode("LLVMXor", CoreJNI.LLVMXor_get());
  public final static LLVMOpcode LLVMAlloca = new LLVMOpcode("LLVMAlloca", CoreJNI.LLVMAlloca_get());
  public final static LLVMOpcode LLVMLoad = new LLVMOpcode("LLVMLoad", CoreJNI.LLVMLoad_get());
  public final static LLVMOpcode LLVMStore = new LLVMOpcode("LLVMStore", CoreJNI.LLVMStore_get());
  public final static LLVMOpcode LLVMGetElementPtr = new LLVMOpcode("LLVMGetElementPtr", CoreJNI.LLVMGetElementPtr_get());
  public final static LLVMOpcode LLVMTrunc = new LLVMOpcode("LLVMTrunc", CoreJNI.LLVMTrunc_get());
  public final static LLVMOpcode LLVMZExt = new LLVMOpcode("LLVMZExt", CoreJNI.LLVMZExt_get());
  public final static LLVMOpcode LLVMSExt = new LLVMOpcode("LLVMSExt", CoreJNI.LLVMSExt_get());
  public final static LLVMOpcode LLVMFPToUI = new LLVMOpcode("LLVMFPToUI", CoreJNI.LLVMFPToUI_get());
  public final static LLVMOpcode LLVMFPToSI = new LLVMOpcode("LLVMFPToSI", CoreJNI.LLVMFPToSI_get());
  public final static LLVMOpcode LLVMUIToFP = new LLVMOpcode("LLVMUIToFP", CoreJNI.LLVMUIToFP_get());
  public final static LLVMOpcode LLVMSIToFP = new LLVMOpcode("LLVMSIToFP", CoreJNI.LLVMSIToFP_get());
  public final static LLVMOpcode LLVMFPTrunc = new LLVMOpcode("LLVMFPTrunc", CoreJNI.LLVMFPTrunc_get());
  public final static LLVMOpcode LLVMFPExt = new LLVMOpcode("LLVMFPExt", CoreJNI.LLVMFPExt_get());
  public final static LLVMOpcode LLVMPtrToInt = new LLVMOpcode("LLVMPtrToInt", CoreJNI.LLVMPtrToInt_get());
  public final static LLVMOpcode LLVMIntToPtr = new LLVMOpcode("LLVMIntToPtr", CoreJNI.LLVMIntToPtr_get());
  public final static LLVMOpcode LLVMBitCast = new LLVMOpcode("LLVMBitCast", CoreJNI.LLVMBitCast_get());
  public final static LLVMOpcode LLVMICmp = new LLVMOpcode("LLVMICmp", CoreJNI.LLVMICmp_get());
  public final static LLVMOpcode LLVMFCmp = new LLVMOpcode("LLVMFCmp", CoreJNI.LLVMFCmp_get());
  public final static LLVMOpcode LLVMPHI = new LLVMOpcode("LLVMPHI", CoreJNI.LLVMPHI_get());
  public final static LLVMOpcode LLVMCall = new LLVMOpcode("LLVMCall", CoreJNI.LLVMCall_get());
  public final static LLVMOpcode LLVMSelect = new LLVMOpcode("LLVMSelect", CoreJNI.LLVMSelect_get());
  public final static LLVMOpcode LLVMUserOp1 = new LLVMOpcode("LLVMUserOp1", CoreJNI.LLVMUserOp1_get());
  public final static LLVMOpcode LLVMUserOp2 = new LLVMOpcode("LLVMUserOp2", CoreJNI.LLVMUserOp2_get());
  public final static LLVMOpcode LLVMVAArg = new LLVMOpcode("LLVMVAArg", CoreJNI.LLVMVAArg_get());
  public final static LLVMOpcode LLVMExtractElement = new LLVMOpcode("LLVMExtractElement", CoreJNI.LLVMExtractElement_get());
  public final static LLVMOpcode LLVMInsertElement = new LLVMOpcode("LLVMInsertElement", CoreJNI.LLVMInsertElement_get());
  public final static LLVMOpcode LLVMShuffleVector = new LLVMOpcode("LLVMShuffleVector", CoreJNI.LLVMShuffleVector_get());
  public final static LLVMOpcode LLVMExtractValue = new LLVMOpcode("LLVMExtractValue", CoreJNI.LLVMExtractValue_get());
  public final static LLVMOpcode LLVMInsertValue = new LLVMOpcode("LLVMInsertValue", CoreJNI.LLVMInsertValue_get());
  public final static LLVMOpcode LLVMFence = new LLVMOpcode("LLVMFence", CoreJNI.LLVMFence_get());
  public final static LLVMOpcode LLVMAtomicCmpXchg = new LLVMOpcode("LLVMAtomicCmpXchg", CoreJNI.LLVMAtomicCmpXchg_get());
  public final static LLVMOpcode LLVMAtomicRMW = new LLVMOpcode("LLVMAtomicRMW", CoreJNI.LLVMAtomicRMW_get());
  public final static LLVMOpcode LLVMResume = new LLVMOpcode("LLVMResume", CoreJNI.LLVMResume_get());
  public final static LLVMOpcode LLVMLandingPad = new LLVMOpcode("LLVMLandingPad", CoreJNI.LLVMLandingPad_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMOpcode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMOpcode.class + " with value " + swigValue);
  }

  private LLVMOpcode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMOpcode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMOpcode(String swigName, LLVMOpcode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMOpcode[] swigValues = { LLVMRet, LLVMBr, LLVMSwitch, LLVMIndirectBr, LLVMInvoke, LLVMUnreachable, LLVMAdd, LLVMFAdd, LLVMSub, LLVMFSub, LLVMMul, LLVMFMul, LLVMUDiv, LLVMSDiv, LLVMFDiv, LLVMURem, LLVMSRem, LLVMFRem, LLVMShl, LLVMLShr, LLVMAShr, LLVMAnd, LLVMOr, LLVMXor, LLVMAlloca, LLVMLoad, LLVMStore, LLVMGetElementPtr, LLVMTrunc, LLVMZExt, LLVMSExt, LLVMFPToUI, LLVMFPToSI, LLVMUIToFP, LLVMSIToFP, LLVMFPTrunc, LLVMFPExt, LLVMPtrToInt, LLVMIntToPtr, LLVMBitCast, LLVMICmp, LLVMFCmp, LLVMPHI, LLVMCall, LLVMSelect, LLVMUserOp1, LLVMUserOp2, LLVMVAArg, LLVMExtractElement, LLVMInsertElement, LLVMShuffleVector, LLVMExtractValue, LLVMInsertValue, LLVMFence, LLVMAtomicCmpXchg, LLVMAtomicRMW, LLVMResume, LLVMLandingPad };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

