/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class LLVMOpInfoSymbol1 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LLVMOpInfoSymbol1(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LLVMOpInfoSymbol1 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DisassemblerJNI.delete_LLVMOpInfoSymbol1(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPresent(SWIGTYPE_p_uint64_t value) {
    DisassemblerJNI.LLVMOpInfoSymbol1_Present_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getPresent() {
    return new SWIGTYPE_p_uint64_t(DisassemblerJNI.LLVMOpInfoSymbol1_Present_get(swigCPtr, this), true);
  }

  public void setName(String value) {
    DisassemblerJNI.LLVMOpInfoSymbol1_Name_set(swigCPtr, this, value);
  }

  public String getName() {
    return DisassemblerJNI.LLVMOpInfoSymbol1_Name_get(swigCPtr, this);
  }

  public void setValue(SWIGTYPE_p_uint64_t value) {
    DisassemblerJNI.LLVMOpInfoSymbol1_Value_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getValue() {
    return new SWIGTYPE_p_uint64_t(DisassemblerJNI.LLVMOpInfoSymbol1_Value_get(swigCPtr, this), true);
  }

  public LLVMOpInfoSymbol1() {
    this(DisassemblerJNI.new_LLVMOpInfoSymbol1(), true);
  }

}
