/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class lto_symbol_attributes {
  public final static lto_symbol_attributes LTO_SYMBOL_ALIGNMENT_MASK = new lto_symbol_attributes("LTO_SYMBOL_ALIGNMENT_MASK", ltoJNI.LTO_SYMBOL_ALIGNMENT_MASK_get());
  public final static lto_symbol_attributes LTO_SYMBOL_PERMISSIONS_MASK = new lto_symbol_attributes("LTO_SYMBOL_PERMISSIONS_MASK", ltoJNI.LTO_SYMBOL_PERMISSIONS_MASK_get());
  public final static lto_symbol_attributes LTO_SYMBOL_PERMISSIONS_CODE = new lto_symbol_attributes("LTO_SYMBOL_PERMISSIONS_CODE", ltoJNI.LTO_SYMBOL_PERMISSIONS_CODE_get());
  public final static lto_symbol_attributes LTO_SYMBOL_PERMISSIONS_DATA = new lto_symbol_attributes("LTO_SYMBOL_PERMISSIONS_DATA", ltoJNI.LTO_SYMBOL_PERMISSIONS_DATA_get());
  public final static lto_symbol_attributes LTO_SYMBOL_PERMISSIONS_RODATA = new lto_symbol_attributes("LTO_SYMBOL_PERMISSIONS_RODATA", ltoJNI.LTO_SYMBOL_PERMISSIONS_RODATA_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_MASK = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_MASK", ltoJNI.LTO_SYMBOL_DEFINITION_MASK_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_REGULAR = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_REGULAR", ltoJNI.LTO_SYMBOL_DEFINITION_REGULAR_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_TENTATIVE = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_TENTATIVE", ltoJNI.LTO_SYMBOL_DEFINITION_TENTATIVE_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_WEAK = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_WEAK", ltoJNI.LTO_SYMBOL_DEFINITION_WEAK_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_UNDEFINED = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_UNDEFINED", ltoJNI.LTO_SYMBOL_DEFINITION_UNDEFINED_get());
  public final static lto_symbol_attributes LTO_SYMBOL_DEFINITION_WEAKUNDEF = new lto_symbol_attributes("LTO_SYMBOL_DEFINITION_WEAKUNDEF", ltoJNI.LTO_SYMBOL_DEFINITION_WEAKUNDEF_get());
  public final static lto_symbol_attributes LTO_SYMBOL_SCOPE_MASK = new lto_symbol_attributes("LTO_SYMBOL_SCOPE_MASK", ltoJNI.LTO_SYMBOL_SCOPE_MASK_get());
  public final static lto_symbol_attributes LTO_SYMBOL_SCOPE_INTERNAL = new lto_symbol_attributes("LTO_SYMBOL_SCOPE_INTERNAL", ltoJNI.LTO_SYMBOL_SCOPE_INTERNAL_get());
  public final static lto_symbol_attributes LTO_SYMBOL_SCOPE_HIDDEN = new lto_symbol_attributes("LTO_SYMBOL_SCOPE_HIDDEN", ltoJNI.LTO_SYMBOL_SCOPE_HIDDEN_get());
  public final static lto_symbol_attributes LTO_SYMBOL_SCOPE_PROTECTED = new lto_symbol_attributes("LTO_SYMBOL_SCOPE_PROTECTED", ltoJNI.LTO_SYMBOL_SCOPE_PROTECTED_get());
  public final static lto_symbol_attributes LTO_SYMBOL_SCOPE_DEFAULT = new lto_symbol_attributes("LTO_SYMBOL_SCOPE_DEFAULT", ltoJNI.LTO_SYMBOL_SCOPE_DEFAULT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static lto_symbol_attributes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + lto_symbol_attributes.class + " with value " + swigValue);
  }

  private lto_symbol_attributes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private lto_symbol_attributes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private lto_symbol_attributes(String swigName, lto_symbol_attributes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static lto_symbol_attributes[] swigValues = { LTO_SYMBOL_ALIGNMENT_MASK, LTO_SYMBOL_PERMISSIONS_MASK, LTO_SYMBOL_PERMISSIONS_CODE, LTO_SYMBOL_PERMISSIONS_DATA, LTO_SYMBOL_PERMISSIONS_RODATA, LTO_SYMBOL_DEFINITION_MASK, LTO_SYMBOL_DEFINITION_REGULAR, LTO_SYMBOL_DEFINITION_TENTATIVE, LTO_SYMBOL_DEFINITION_WEAK, LTO_SYMBOL_DEFINITION_UNDEFINED, LTO_SYMBOL_DEFINITION_WEAKUNDEF, LTO_SYMBOL_SCOPE_MASK, LTO_SYMBOL_SCOPE_INTERNAL, LTO_SYMBOL_SCOPE_HIDDEN, LTO_SYMBOL_SCOPE_PROTECTED, LTO_SYMBOL_SCOPE_DEFAULT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

