/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <llvm-c/lto.h>


static char * *new_StringArray(int nelements) { 
  return (char * *) calloc(nelements,sizeof(char *)); 
}

static void delete_StringArray(char * *ary) { 
  free(ary); 
}

static char * StringArray_getitem(char * *ary, int index) {
    return ary[index];
}
static void StringArray_setitem(char * *ary, int index, char * value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_new_1StringArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char **)new_StringArray(arg1);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_delete_1StringArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  char **arg1 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  delete_StringArray(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_ltoJNI_StringArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jstring jresult = 0 ;
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)StringArray_getitem(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_StringArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3) {
  char **arg1 = (char **) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  StringArray_setitem(arg1,arg2,arg3);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1H_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1API_1VERSION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1ALIGNMENT_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_ALIGNMENT_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1PERMISSIONS_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_PERMISSIONS_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1PERMISSIONS_1CODE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_PERMISSIONS_CODE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1PERMISSIONS_1DATA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_PERMISSIONS_DATA;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1PERMISSIONS_1RODATA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_PERMISSIONS_RODATA;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1REGULAR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_REGULAR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1TENTATIVE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_TENTATIVE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1WEAK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_WEAK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1UNDEFINED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_UNDEFINED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1DEFINITION_1WEAKUNDEF_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_DEFINITION_WEAKUNDEF;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1MASK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_MASK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1INTERNAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_INTERNAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1HIDDEN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_HIDDEN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1PROTECTED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_PROTECTED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1DEFAULT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_DEFAULT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1SYMBOL_1SCOPE_1DEFAULT_1CAN_1BE_1HIDDEN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_symbol_attributes)LTO_SYMBOL_SCOPE_DEFAULT_CAN_BE_HIDDEN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1DEBUG_1MODEL_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_debug_model result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_debug_model)LTO_DEBUG_MODEL_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1DEBUG_1MODEL_1DWARF_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_debug_model result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_debug_model)LTO_DEBUG_MODEL_DWARF;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1CODEGEN_1PIC_1MODEL_1STATIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_codegen_model result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_codegen_model)LTO_CODEGEN_PIC_MODEL_STATIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1CODEGEN_1PIC_1MODEL_1DYNAMIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_codegen_model result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_codegen_model)LTO_CODEGEN_PIC_MODEL_DYNAMIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_LTO_1CODEGEN_1PIC_1MODEL_1DYNAMIC_1NO_1PIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  lto_codegen_model result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_codegen_model)LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1get_1version(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)lto_get_version();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1get_1error_1message(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)lto_get_error_message();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1is_1object_1file(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jboolean jresult = 0 ;
  char *arg1 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (bool)lto_module_is_object_file((char const *)arg1);
  jresult = (jboolean)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1is_1object_1file_1for_1target(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jboolean jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)lto_module_is_object_file_for_target((char const *)arg1,(char const *)arg2);
  jresult = (jboolean)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1is_1object_1file_1in_1memory(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (bool)lto_module_is_object_file_in_memory((void const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1is_1object_1file_1in_1memory_1for_1target(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jboolean jresult = 0 ;
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  char *arg3 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (bool)lto_module_is_object_file_in_memory_for_target((void const *)arg1,arg2,(char const *)arg3);
  jresult = (jboolean)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1create(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  lto_module_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (lto_module_t)lto_module_create((char const *)arg1);
  *(lto_module_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1create_1from_1memory(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  lto_module_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (lto_module_t)lto_module_create_from_memory((void const *)arg1,arg2);
  *(lto_module_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1create_1from_1fd(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  lto_module_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  result = (lto_module_t)lto_module_create_from_fd(arg1,(char const *)arg2,arg3);
  *(lto_module_t *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1create_1from_1fd_1at_1offset(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  size_t arg3 ;
  size_t arg4 ;
  off_t arg5 ;
  off_t *argp5 ;
  lto_module_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (size_t)jarg3; 
  arg4 = (size_t)jarg4; 
  argp5 = *(off_t **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null off_t");
    return 0;
  }
  arg5 = *argp5; 
  result = (lto_module_t)lto_module_create_from_fd_at_offset(arg1,(char const *)arg2,arg3,arg4,arg5);
  *(lto_module_t *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1dispose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  lto_module_t arg1 = (lto_module_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  lto_module_dispose(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1get_1target_1triple(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  lto_module_t arg1 = (lto_module_t) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  result = (char *)lto_module_get_target_triple(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1set_1target_1triple(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lto_module_t arg1 = (lto_module_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lto_module_set_target_triple(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1get_1num_1symbols(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  lto_module_t arg1 = (lto_module_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  result = (unsigned int)lto_module_get_num_symbols(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1get_1symbol_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  lto_module_t arg1 = (lto_module_t) 0 ;
  unsigned int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (char *)lto_module_get_symbol_name(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1module_1get_1symbol_1attribute(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  lto_module_t arg1 = (lto_module_t) 0 ;
  unsigned int arg2 ;
  lto_symbol_attributes result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_module_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (lto_symbol_attributes)lto_module_get_symbol_attribute(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  lto_code_gen_t result;
  
  (void)jenv;
  (void)jcls;
  result = (lto_code_gen_t)lto_codegen_create();
  *(lto_code_gen_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1dispose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  lto_codegen_dispose(arg1);
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1add_1module(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  lto_module_t arg2 = (lto_module_t) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = *(lto_module_t *)&jarg2; 
  result = (bool)lto_codegen_add_module(arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1set_1debug_1model(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jboolean jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  lto_debug_model arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = (lto_debug_model)jarg2; 
  result = (bool)lto_codegen_set_debug_model(arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1set_1pic_1model(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jboolean jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  lto_codegen_model arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = (lto_codegen_model)jarg2; 
  result = (bool)lto_codegen_set_pic_model(arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1set_1cpu(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lto_codegen_set_cpu(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1set_1assembler_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lto_codegen_set_assembler_path(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1set_1assembler_1args(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char **arg2 = (char **) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  arg3 = (int)jarg3; 
  lto_codegen_set_assembler_args(arg1,(char const **)arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1add_1must_1preserve_1symbol(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lto_codegen_add_must_preserve_symbol(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1write_1merged_1modules(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jboolean jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)lto_codegen_write_merged_modules(arg1,(char const *)arg2);
  jresult = (jboolean)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1compile(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  result = (void *)lto_codegen_compile(arg1,arg2);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1compile_1to_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char **arg2 = (char **) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (bool)lto_codegen_compile_to_file(arg1,(char const **)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_jllvm_bindings_ltoJNI_lto_1codegen_1debug_1options(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  lto_code_gen_t arg1 = (lto_code_gen_t) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(lto_code_gen_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  lto_codegen_debug_options(arg1,(char const *)arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


#ifdef __cplusplus
}
#endif

