/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public interface ltoConstants {
  public final static int LTO_H = ltoJNI.LTO_H_get();
  public final static int LTO_API_VERSION = ltoJNI.LTO_API_VERSION_get();
}
