/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Object {
  public static SWIGTYPE_p_LLVMOpaqueObjectFile LLVMCreateObjectFile(SWIGTYPE_p_LLVMMemoryBufferRef MemBuf) {
    long cPtr = ObjectJNI.LLVMCreateObjectFile(SWIGTYPE_p_LLVMMemoryBufferRef.getCPtr(MemBuf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueObjectFile(cPtr, false);
  }

  public static void LLVMDisposeObjectFile(SWIGTYPE_p_LLVMOpaqueObjectFile ObjectFile) {
    ObjectJNI.LLVMDisposeObjectFile(SWIGTYPE_p_LLVMOpaqueObjectFile.getCPtr(ObjectFile));
  }

  public static SWIGTYPE_p_LLVMOpaqueSectionIterator LLVMGetSections(SWIGTYPE_p_LLVMOpaqueObjectFile ObjectFile) {
    long cPtr = ObjectJNI.LLVMGetSections(SWIGTYPE_p_LLVMOpaqueObjectFile.getCPtr(ObjectFile));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueSectionIterator(cPtr, false);
  }

  public static void LLVMDisposeSectionIterator(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    ObjectJNI.LLVMDisposeSectionIterator(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI));
  }

  public static int LLVMIsSectionIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueObjectFile ObjectFile, SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    return ObjectJNI.LLVMIsSectionIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueObjectFile.getCPtr(ObjectFile), SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI));
  }

  public static void LLVMMoveToNextSection(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    ObjectJNI.LLVMMoveToNextSection(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI));
  }

  public static void LLVMMoveToContainingSection(SWIGTYPE_p_LLVMOpaqueSectionIterator Sect, SWIGTYPE_p_LLVMOpaqueSymbolIterator Sym) {
    ObjectJNI.LLVMMoveToContainingSection(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(Sect), SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(Sym));
  }

  public static SWIGTYPE_p_LLVMOpaqueSymbolIterator LLVMGetSymbols(SWIGTYPE_p_LLVMOpaqueObjectFile ObjectFile) {
    long cPtr = ObjectJNI.LLVMGetSymbols(SWIGTYPE_p_LLVMOpaqueObjectFile.getCPtr(ObjectFile));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueSymbolIterator(cPtr, false);
  }

  public static void LLVMDisposeSymbolIterator(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    ObjectJNI.LLVMDisposeSymbolIterator(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI));
  }

  public static int LLVMIsSymbolIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueObjectFile ObjectFile, SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    return ObjectJNI.LLVMIsSymbolIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueObjectFile.getCPtr(ObjectFile), SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI));
  }

  public static void LLVMMoveToNextSymbol(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    ObjectJNI.LLVMMoveToNextSymbol(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI));
  }

  public static String LLVMGetSectionName(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    return ObjectJNI.LLVMGetSectionName(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI));
  }

  public static SWIGTYPE_p_uint64_t LLVMGetSectionSize(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetSectionSize(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI)), true);
  }

  public static String LLVMGetSectionContents(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    return ObjectJNI.LLVMGetSectionContents(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI));
  }

  public static SWIGTYPE_p_uint64_t LLVMGetSectionAddress(SWIGTYPE_p_LLVMOpaqueSectionIterator SI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetSectionAddress(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI)), true);
  }

  public static int LLVMGetSectionContainsSymbol(SWIGTYPE_p_LLVMOpaqueSectionIterator SI, SWIGTYPE_p_LLVMOpaqueSymbolIterator Sym) {
    return ObjectJNI.LLVMGetSectionContainsSymbol(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(SI), SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(Sym));
  }

  public static SWIGTYPE_p_LLVMOpaqueRelocationIterator LLVMGetRelocations(SWIGTYPE_p_LLVMOpaqueSectionIterator Section) {
    long cPtr = ObjectJNI.LLVMGetRelocations(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(Section));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueRelocationIterator(cPtr, false);
  }

  public static void LLVMDisposeRelocationIterator(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    ObjectJNI.LLVMDisposeRelocationIterator(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
  }

  public static int LLVMIsRelocationIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueSectionIterator Section, SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return ObjectJNI.LLVMIsRelocationIteratorAtEnd(SWIGTYPE_p_LLVMOpaqueSectionIterator.getCPtr(Section), SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
  }

  public static void LLVMMoveToNextRelocation(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    ObjectJNI.LLVMMoveToNextRelocation(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
  }

  public static String LLVMGetSymbolName(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    return ObjectJNI.LLVMGetSymbolName(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI));
  }

  public static SWIGTYPE_p_uint64_t LLVMGetSymbolAddress(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetSymbolAddress(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI)), true);
  }

  public static SWIGTYPE_p_uint64_t LLVMGetSymbolFileOffset(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetSymbolFileOffset(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI)), true);
  }

  public static SWIGTYPE_p_uint64_t LLVMGetSymbolSize(SWIGTYPE_p_LLVMOpaqueSymbolIterator SI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetSymbolSize(SWIGTYPE_p_LLVMOpaqueSymbolIterator.getCPtr(SI)), true);
  }

  public static SWIGTYPE_p_uint64_t LLVMGetRelocationAddress(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetRelocationAddress(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI)), true);
  }

  public static SWIGTYPE_p_uint64_t LLVMGetRelocationOffset(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetRelocationOffset(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI)), true);
  }

  public static SWIGTYPE_p_LLVMOpaqueSymbolIterator LLVMGetRelocationSymbol(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    long cPtr = ObjectJNI.LLVMGetRelocationSymbol(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueSymbolIterator(cPtr, false);
  }

  public static SWIGTYPE_p_uint64_t LLVMGetRelocationType(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return new SWIGTYPE_p_uint64_t(ObjectJNI.LLVMGetRelocationType(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI)), true);
  }

  public static String LLVMGetRelocationTypeName(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return ObjectJNI.LLVMGetRelocationTypeName(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
  }

  public static String LLVMGetRelocationValueString(SWIGTYPE_p_LLVMOpaqueRelocationIterator RI) {
    return ObjectJNI.LLVMGetRelocationValueString(SWIGTYPE_p_LLVMOpaqueRelocationIterator.getCPtr(RI));
  }

}
