/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Target {
  public static void LLVMInitializeAllTargetInfos() {
    TargetJNI.LLVMInitializeAllTargetInfos();
  }

  public static void LLVMInitializeAllTargets() {
    TargetJNI.LLVMInitializeAllTargets();
  }

  public static void LLVMInitializeAllTargetMCs() {
    TargetJNI.LLVMInitializeAllTargetMCs();
  }

  public static void LLVMInitializeAllAsmPrinters() {
    TargetJNI.LLVMInitializeAllAsmPrinters();
  }

  public static void LLVMInitializeAllAsmParsers() {
    TargetJNI.LLVMInitializeAllAsmParsers();
  }

  public static void LLVMInitializeAllDisassemblers() {
    TargetJNI.LLVMInitializeAllDisassemblers();
  }

  public static int LLVMInitializeNativeTarget() {
    return TargetJNI.LLVMInitializeNativeTarget();
  }

  public static SWIGTYPE_p_LLVMOpaqueTargetData LLVMCreateTargetData(String StringRep) {
    long cPtr = TargetJNI.LLVMCreateTargetData(StringRep);
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueTargetData(cPtr, false);
  }

  public static void LLVMAddTargetData(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaquePassManager arg1) {
    TargetJNI.LLVMAddTargetData(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(arg1));
  }

  public static void LLVMAddTargetLibraryInfo(SWIGTYPE_p_LLVMOpaqueTargetLibraryInfotData arg0, SWIGTYPE_p_LLVMOpaquePassManager arg1) {
    TargetJNI.LLVMAddTargetLibraryInfo(SWIGTYPE_p_LLVMOpaqueTargetLibraryInfotData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaquePassManager.getCPtr(arg1));
  }

  public static String LLVMCopyStringRepOfTargetData(SWIGTYPE_p_LLVMOpaqueTargetData arg0) {
    return TargetJNI.LLVMCopyStringRepOfTargetData(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0));
  }

  public static LLVMByteOrdering LLVMByteOrder(SWIGTYPE_p_LLVMOpaqueTargetData arg0) {
    return LLVMByteOrdering.swigToEnum(TargetJNI.LLVMByteOrder(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0)));
  }

  public static long LLVMPointerSize(SWIGTYPE_p_LLVMOpaqueTargetData arg0) {
    return TargetJNI.LLVMPointerSize(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0));
  }

  public static SWIGTYPE_p_LLVMOpaqueType LLVMIntPtrType(SWIGTYPE_p_LLVMOpaqueTargetData arg0) {
    long cPtr = TargetJNI.LLVMIntPtrType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMOpaqueType(cPtr, false);
  }

  public static java.math.BigInteger LLVMSizeOfTypeInBits(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMSizeOfTypeInBits(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static java.math.BigInteger LLVMStoreSizeOfType(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMStoreSizeOfType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static java.math.BigInteger LLVMABISizeOfType(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMABISizeOfType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static long LLVMABIAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMABIAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static long LLVMCallFrameAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMCallFrameAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static long LLVMPreferredAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType arg1) {
    return TargetJNI.LLVMPreferredAlignmentOfType(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(arg1));
  }

  public static long LLVMPreferredAlignmentOfGlobal(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueValue GlobalVar) {
    return TargetJNI.LLVMPreferredAlignmentOfGlobal(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueValue.getCPtr(GlobalVar));
  }

  public static long LLVMElementAtOffset(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType StructTy, java.math.BigInteger Offset) {
    return TargetJNI.LLVMElementAtOffset(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(StructTy), Offset);
  }

  public static java.math.BigInteger LLVMOffsetOfElement(SWIGTYPE_p_LLVMOpaqueTargetData arg0, SWIGTYPE_p_LLVMOpaqueType StructTy, long Element) {
    return TargetJNI.LLVMOffsetOfElement(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0), SWIGTYPE_p_LLVMOpaqueType.getCPtr(StructTy), Element);
  }

  public static void LLVMDisposeTargetData(SWIGTYPE_p_LLVMOpaqueTargetData arg0) {
    TargetJNI.LLVMDisposeTargetData(SWIGTYPE_p_LLVMOpaqueTargetData.getCPtr(arg0));
  }

}
