/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

class IPOJNI {
  public final static native void LLVMAddArgumentPromotionPass(long jarg1);
  public final static native void LLVMAddConstantMergePass(long jarg1);
  public final static native void LLVMAddDeadArgEliminationPass(long jarg1);
  public final static native void LLVMAddDeadTypeEliminationPass(long jarg1);
  public final static native void LLVMAddFunctionAttrsPass(long jarg1);
  public final static native void LLVMAddFunctionInliningPass(long jarg1);
  public final static native void LLVMAddGlobalDCEPass(long jarg1);
  public final static native void LLVMAddGlobalOptimizerPass(long jarg1);
  public final static native void LLVMAddIPConstantPropagationPass(long jarg1);
  public final static native void LLVMAddLowerSetJmpPass(long jarg1);
  public final static native void LLVMAddPruneEHPass(long jarg1);
  public final static native void LLVMAddRaiseAllocationsPass(long jarg1);
  public final static native void LLVMAddStripDeadPrototypesPass(long jarg1);
  public final static native void LLVMAddStripSymbolsPass(long jarg1);
}
