/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings.Transforms;

public class VectorizeJNI {
  public final static native void LLVMAddBBVectorizePass(long jarg1);
  public final static native void LLVMAddLoopVectorizePass(long jarg1);
}
